### ISSUE TITLE
setToken method does not work

### ISSUE THREAD

**Issue by fimdomeio** [VM9/orion-explorer-php-frame-work#6]
I believe this is caused by the fact that at Orion/Utils/HttpRequest the getDefaultHeader method is joining the arrays via the + operator which overwrites the key. I believe it should be doing an `return array_merge($default, $this->custonHeader);` instead.

**Comment by LeonanCarvalho** [comment]
The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored.

Its equivalent to :

```PHP
array_merget($this->custonHeader, $default);//The default headers  coul'd not be replaced
```
You must use PHP5.3+ to run this codes ( I recommend lastest 5.6)

I think your problem is the same of Issue #3

We must implement an oAuth2.0 client to get valid tokens and access Orion API.

**Comment by tania-pets** [comment]
```($default + $this->custonHeader)```  would work if the header arrays (```$default, $this->custonHeader```) had string type keys, e.g :

array (size=2)
  'Content-Type' => string 'application/xml' (length=29)
  'Accept' => string 'application/xml' (length=23)
  
But in our case, the arrays have numeric keys
```$default: 
array (size=2)
  0 => string 'Content-Type: application/xml' (length=29)
  1 => string 'Accept: application/xml' (length=23)```
  
$this->custonHeader:
array (size=1)
  0 => string 'X-Auth-Token: xxxxxxxx' (length=44)
  
So the '0' index is kept from left hand $default array and as a result X-Auth-Token is never added.

**Comment by LeonanCarvalho** [comment]
Few months ago before github the headers were extored on a string key's array. I don't remember why it was changed to numeric keys arrays. 
@tania-pets  Thanks for your explanation.
